cargo: remove default features
Remove default features to force crate users to select proper MCU.
Besides, removal of default MCU selection helps to fix
the following error:

error: symbol `DEVICE_PERIPHERALS` is already defined
      -->
/home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/stm32l1-0.5.0/src/stm32l162/mod.rs:155747:1
       |
155747 | static mut DEVICE_PERIPHERALS: bool = false;
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

With default MCU selection such an issue could be eliminated
only by the use of --no-default-features switch.

Signed-off-by: Sergey Matyukevich <geomatsi@gmail.com>